type: SDXL_FINETUNE
seed: 1
base_output_dir: output/baroque/sdxl_finetune

optimizer:
  optimizer_type: AdamW
  learning_rate: 1e-4
  weight_decay: 1e-3
  use_8bit: True

lr_scheduler: constant_with_warmup
lr_warmup_steps: 200

data_loader:
  type: IMAGE_CAPTION_SD_DATA_LOADER
  dataset:
    type: IMAGE_CAPTION_JSONL_DATASET
    # Update the jsonl_path field to point to the metadata.jsonl file of the downloaded dataset.
    jsonl_path: data/nga-baroque/metadata.jsonl
  resolution: 1024
  aspect_ratio_buckets:
    target_resolution: 1024
    start_dim: 512
    end_dim: 1536
    divisible_by: 128
  caption_prefix: "A b4r0que painting of"

# General
model: stabilityai/stable-diffusion-xl-base-1.0
# vae_model: madebyollin/sdxl-vae-fp16-fix
gradient_accumulation_steps: 1
weight_dtype: bfloat16
gradient_checkpointing: True
cache_vae_outputs: True
cache_text_encoder_outputs: True

max_train_epochs: 24
# Currently, we set save_every_n_epochs to a large value so that we don't save any checkpoints. They take up lots of
# disk space, so this config is just intended for viewing the validation images.
save_every_n_epochs: 100
validate_every_n_epochs: 2

max_checkpoints: 0
validation_prompts:
  - A b4r0que painting of a woman carrying a basket of fruit.
  - A b4r0que painting of a cute Yoda creature.
train_batch_size: 4
num_validation_images_per_prompt: 3
