# Training mode: Full Finetuning
# Base model:    SDXL
# Dataset:       https://huggingface.co/datasets/InvokeAI/nga-baroque
# GPU:           1 x 24GB

# Instructions:
# 1. Download the dataset from https://huggingface.co/datasets/InvokeAI/nga-baroque.
# 2. Update the `jsonl_path` field in the `data_loader` section to point to the `metadata.jsonl` file of the downloaded
# dataset.

type: SDXL_FINETUNE
seed: 1
base_output_dir: output/baroque/sdxl_finetune

optimizer:
  optimizer_type: AdamW
  learning_rate: 5e-5
  weight_decay: 1e-3
  use_8bit: True

lr_scheduler: constant_with_warmup
lr_warmup_steps: 500

data_loader:
  type: IMAGE_CAPTION_SD_DATA_LOADER
  dataset:
    type: IMAGE_CAPTION_JSONL_DATASET
    # Update the jsonl_path field to point to the metadata.jsonl file of the downloaded dataset.
    jsonl_path: data/nga-baroque/metadata.jsonl
  resolution: 1024
  aspect_ratio_buckets:
    target_resolution: 1024
    start_dim: 512
    end_dim: 1536
    divisible_by: 128
  caption_prefix: "A baroque style painting,"

# General
model: stabilityai/stable-diffusion-xl-base-1.0
save_checkpoint_format: trained_only_diffusers
# vae_model: madebyollin/sdxl-vae-fp16-fix
save_dtype: float16
gradient_accumulation_steps: 1
weight_dtype: bfloat16
gradient_checkpointing: True
cache_vae_outputs: True
cache_text_encoder_outputs: True

max_train_epochs: 50
save_every_n_epochs: 3
validate_every_n_epochs: 3
# We save a max of 1 checkpoint for demo purposes, because the checkpoints take up a lot of disk space.
max_checkpoints: 1

validation_prompts:
  - A baroque style painting of a woman carrying a basket of fruit.
  - A baroque style painting of a cute Yoda creature.
train_batch_size: 4
num_validation_images_per_prompt: 3
