# Training mode: Direct Preference Optimization LoRA Training
# Base model:    SD 1.5
# GPU:           1 x 24GB

type: DIRECT_PREFERENCE_OPTIMIZATION_LORA_SD
seed: 1
base_output_dir: output/dpo

optimizer:
  optimizer_type: AdamW
  learning_rate: 1e-4
  weight_decay: 1e-2

lr_warmup_steps: 500
lr_scheduler: cosine

data_loader:
  type: IMAGE_PAIR_PREFERENCE_SD_DATA_LOADER
  dataset:
    type: IMAGE_PAIR_PREFERENCE_DATASET
    dataset_dir: output/pokemon_pairs
  resolution: 512
  dataloader_num_workers: 4

# General
model: runwayml/stable-diffusion-v1-5
initial_lora: output/finetune_lora_sd_pokemon/1704824279.2765746/checkpoint_epoch-00000003
gradient_accumulation_steps: 2
mixed_precision: fp16
xformers: False
gradient_checkpointing: True
max_train_steps: 5000
save_every_n_epochs: 10
save_every_n_steps: null
max_checkpoints: 100
validation_prompts:
  - A cute yoda pokemon creature.
  - A cute astronaut pokemon creature.
validate_every_n_epochs: 10
train_batch_size: 4
num_validation_images_per_prompt: 2
