site_name: invoke-training
site_url: https://invoke-ai.github.io/invoke-training/

repo_name: invoke-ai/invoke-training
repo_url: https://github.com/invoke-ai/invoke-training

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes

markdown_extensions:
  - sane_lists

nav:
- Welcome: index.md
- Get Started:
  - get_started/installation.md
  - get_started/quick_start.md
- Tutorials:
  - tutorials/index.md
  - Stable Diffusion:
    - tutorials/stable_diffusion/finetune_lora_sd.md
    - tutorials/stable_diffusion/dreambooth_lora_sd.md
    - tutorials/stable_diffusion/textual_inversion_sd.md
    - tutorials/stable_diffusion/pivotal_tuning_sd.md
    - tutorials/stable_diffusion/the_chosen_one_sd.md
- Concepts:
  - concepts/dataset_formats.md
- Config Reference:
  - reference/config/index.md
  - Pipeline Configs:
    - Finetune LoRA - Stable Diffusion v1/v2: reference/config/pipelines/finetune_lora_sd_config.md
    - Finetune LoRA - Stable Diffusion XL: reference/config/pipelines/finetune_lora_sdxl_config.md
    - Textual Inversion - Stable Diffusion v1/v2: reference/config/pipelines/textual_inversion_sd_config.md
- Contributing:
  - contributing/development_environment.md
  - contributing/directory_structure.md
  - contributing/tests.md
  - contributing/documentation.md

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_bases: false
          show_source: false
          show_if_no_docstring: true
          inherited_members: true
          annotations_path: brief
          separate_signature: true
          show_signature_annotations: true
