site_name: invoke-training
site_url: https://invoke-ai.github.io/invoke-training/

repo_name: invoke-ai/invoke-training
repo_url: https://github.com/invoke-ai/invoke-training

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - admonition
  - sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
- Welcome: index.md
- Get Started:
  - get_started/installation.md
  - get_started/quick_start.md
- Tutorials:
  - tutorials/index.md
  - Stable Diffusion:
    # - tutorials/stable_diffusion/finetune_lora_sd.md
    # - tutorials/stable_diffusion/dreambooth_lora_sd.md
    - tutorials/stable_diffusion/textual_inversion_sdxl.md
    # - tutorials/stable_diffusion/pivotal_tuning_sd.md
    # - tutorials/stable_diffusion/the_chosen_one_sd.md
    - tutorials/stable_diffusion/dpo_lora_sd.md
- Concepts:
  - concepts/index.md
  - concepts/dataset_formats.md
- YAML Config Reference:
  - reference/config/index.md
  - pipelines:
    - SD LoRA Config: reference/config/pipelines/sd_lora.md
    - SD Textual Inversion Config: reference/config/pipelines/sd_textual_inversion.md
    - SDXL LoRA Config: reference/config/pipelines/sdxl_lora.md
    - SDXL Textual Inversion Config: reference/config/pipelines/sdxl_textual_inversion.md
    - SDXL LoRA and Textual Inversion Config: reference/config/pipelines/sdxl_lora_and_textual_inversion.md
  - shared:
    - data_loader_config: reference/config/shared/data/data_loader_config.md
    - dataset_config: reference/config/shared/data/dataset_config.md
    - optimizer_config: reference/config/shared/optimizer_config.md
- Contributing:
  - contributing/development_environment.md
  - contributing/directory_structure.md
  - contributing/tests.md
  - contributing/documentation.md

plugins:
- search
- mkdocstrings:
    default_handler: python
    custom_templates: docs/templates
    handlers:
      python:
        options:
          show_root_heading: false
          show_root_toc_entry: false
          show_bases: false
          show_source: false
          show_if_no_docstring: true
          inherited_members: true
          annotations_path: brief
          separate_signature: true
          show_signature_annotations: true
          members_order: source
