[build-system]
requires = ["setuptools>=65.5", "pip>=22.3"]
build-backend = "setuptools.build_meta"

[project]
name = "invoke-training"
version = "0.0.1"
authors = [
    { name="The Invoke AI Team", email="ryan@invoke.ai" },
]
description = "A library for Stable Diffusion model training."
readme = "README.md"
requires-python = ">=3.9"
license = {text = "Apache-2.0"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "torch~=2.0.1",
]

[project.optional-dependencies]
"test" = [
    "black~=23.7.0",
    "isort~=5.12.0",
    "pytest~=7.4.0",
    "ruff~=0.0.281",
]

[project.scripts]
"invoke-train-lora" = "invoke_training.scripts.invoke_train_lora:main"

[project.urls]
"Homepage" = "https://github.com/invoke-ai/invoke-training"
"Discord" = "https://discord.gg/ZmtBAhwWhy"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.ruff]
select = ["E", "F", "W", "C9", "N8"]
target-version = "py39"
line-length = 120

[tool.pytest.ini_options]
addopts = "--strict-markers"
markers = [
    "cuda: marks tests that require a CUDA GPU",
]
