type: SDXL_LORA
seed: 1
base_output_dir: output/mohrbacher/

# optimizer:
#   optimizer_type: Prodigy
#   learning_rate: 1.0
#   weight_decay: 0.01
#   use_bias_correction: True
#   safeguard_warmup: True
optimizer:
  optimizer_type: AdamW
  learning_rate: 4e-3

lr_scheduler: constant_with_warmup
lr_warmup_steps: 200

text_encoder_learning_rate: 1e-3
unet_learning_rate: 1e-3

# data_loader:
#   type: IMAGE_CAPTION_SD_DATA_LOADER
#   dataset:
#     type: HF_HUB_IMAGE_CAPTION_DATASET
#     dataset_name: lambdalabs/pokemon-blip-captions
#   resolution: 512
#   dataloader_num_workers: 4
data_loader:
  type: IMAGE_CAPTION_SD_DATA_LOADER
  dataset:
    type: IMAGE_CAPTION_JSONL_DATASET
    jsonl_path: /home/ryan/data/hf_mohrbacher_full_size/metadata.jsonl
    image_column: file_name
    caption_column: text
  resolution: 1024
  dataloader_num_workers: 4

  aspect_ratio_buckets:
    target_resolution: 1024
    start_dim: 512
    end_dim: 1536
    divisible_by: 128

# General
model: stabilityai/stable-diffusion-xl-base-1.0
vae_model: madebyollin/sdxl-vae-fp16-fix
gradient_accumulation_steps: 1
mixed_precision: fp16
xformers: False
gradient_checkpointing: True


max_train_epochs: 50
save_every_n_epochs: 1000
validate_every_n_epochs: 1
max_checkpoints: 1

validation_prompts:
  - a surreal digital painting of a robot angel with a halo above her faceless geometric head by mohrbacher
  - a surreal digital painting of an angel wearing an armored red dress with a cloudy sunrise in the background by mohrbacher
train_batch_size: 4
num_validation_images_per_prompt: 3
