type: SD_LORA
seed: 1
base_output_dir: output/preset

optimizer:
  optimizer_type: AdamW
  learning_rate: 4e-3

lr_scheduler: constant_with_warmup
lr_warmup_steps: 200

text_encoder_learning_rate: 1e-3
unet_learning_rate: 1e-3

data_loader:
  type: IMAGE_CAPTION_SD_DATA_LOADER
  dataset:
    type: IMAGE_CAPTION_JSONL_DATASET
    # To be overriden:
    jsonl_path: /path/to/data.jsonl
  resolution: 512
  dataloader_num_workers: 4
  center_crop: False
  random_flip: False

  aspect_ratio_buckets:
    target_resolution: 512
    start_dim: 256
    end_dim: 768
    divisible_by: 64

# General
model: runwayml/stable-diffusion-v1-5
gradient_accumulation_steps: 1
mixed_precision: fp16
xformers: False
gradient_checkpointing: False

train_batch_size: 4

# To be overriden:
max_train_epochs: 50
save_every_n_epochs: 50
validate_every_n_epochs: 3
max_checkpoints: 1

# To be overriden:
validation_prompts:
  - <TODO>
  - <TODO>

num_validation_images_per_prompt: 3
