# Training mode: Textual Inversion
# Base model:    SD v1
# GPU:           1 x 24GB

type: TEXTUAL_INVERSION_SD
seed: 1
output:
  base_output_dir: output/ti_sd_bruce_the_gnome

optimizer:
  learning_rate: 4e-3
  lr_warmup_steps: 200
  lr_scheduler: cosine

  optimizer:
    optimizer_type: AdamW

data_loader:
  type: TEXTUAL_INVERSION_SD_DATA_LOADER
  dataset:
    type: IMAGE_DIR_DATASET
    dataset_dir: "sample_data/bruce_the_gnome"
  captions:
    type: TEXTUAL_INVERSION_PRESET_CAPTION_TRANSFORM
    preset: object
  image_transforms:
    resolution: 512
    center_crop: True
    random_flip: False
  shuffle_caption_transform: null
  aspect_ratio_buckets:
    target_resolution: 512
    start_dim: 256
    end_dim: 768
    divisible_by: 64
  dataloader_num_workers: 4

# General
model: runwayml/stable-diffusion-v1-5
num_vectors: 4
placeholder_token: "bruce_the_gnome"
initializer_token: "gnome"
cache_vae_outputs: False
gradient_accumulation_steps: 1
mixed_precision: fp16
xformers: True
gradient_checkpointing: True
max_train_steps: 2000
save_every_n_epochs: 50
save_every_n_steps: null
max_checkpoints: 200
validation_prompts:
  - A photo of bruce_the_gnome at the beach
  - A photo of bruce_the_gnome reading a book
validate_every_n_epochs: 50
train_batch_size: 1
num_validation_images_per_prompt: 3
