# Training mode: Textual Inversion
# Base model:    SDXL
# GPU:           1 x 24GB
type: TEXTUAL_INVERSION_SDXL
seed: 1
output:
  base_output_dir: output/ti_bruce_the_gnome

optimizer:
  learning_rate: 2e-3
  lr_warmup_steps: 100
  lr_scheduler: cosine

  optimizer:
    optimizer_type: AdamW

data_loader:
  type: TEXTUAL_INVERSION_SDXL_DATA_LOADER
  dataset:
    type: IMAGE_DIR_DATASET
    # dataset_dir: "/home/ryan/data/ryan_db_v7"
    dataset_dir: "sample_data/bruce_the_gnome"
  captions:
    type: TEXTUAL_INVERSION_PRESET_CAPTION_TRANSFORM
    preset: object
  image_transforms:
    resolution: 1024
    center_crop: True
    random_flip: False
  shuffle_caption_transform: null

# General
model: stabilityai/stable-diffusion-xl-base-1.0
vae_model: madebyollin/sdxl-vae-fp16-fix
num_vectors: 1
placeholder_token: "<bruce_the_gnome>"
initializer_token: "gnome"
learnable_property: "object"
cache_vae_outputs: True
gradient_accumulation_steps: 4
mixed_precision: fp16
xformers: True
gradient_checkpointing: True
max_train_steps: 800
save_every_n_epochs: 50
save_every_n_steps: null
max_checkpoints: 200
validation_resolution: 512
validation_prompts:
  - A photo of <bruce_the_gnome> at the beach
  - A photo of <bruce_the_gnome> reading a book
validate_every_n_epochs: 10
train_batch_size: 1
num_validation_images_per_prompt: 3
